# Generated by Django 4.1.3 on 2022-12-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0002_alter_student_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studclass',
            old_name='name',
            new_name='stud_class_name',
        ),
        migrations.AddField(
            model_name='student',
            name='stud_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facerecognition.studclass'),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='stud_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facerecognition.studclass'),
        ),
    ]
