# Generated by Django 4.1.3 on 2022-12-22 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0003_rename_name_studclass_stud_class_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheruser',
            name='stud_class',
        ),
        migrations.AddField(
            model_name='studclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
