# Generated by Django 4.1.3 on 2022-12-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0004_remove_teacheruser_stud_class_studclass_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stud_class',
            new_name='stud_class_name',
        ),
    ]
