# Generated by Django 4.1.3 on 2022-12-15 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0002_teacher_alter_customuser_fav_color_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 12, 15), null=True),
        ),
        migrations.CreateModel(
            name='StudClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facerecognition.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='studclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facerecognition.studclass'),
        ),
    ]
