# Generated by Django 4.1.3 on 2022-12-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0003_remove_student_teacher_alter_student_dob_studclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studclass',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facerecognition.studclass', to_field='name'),
        ),
    ]
