# Generated by Django 4.1.3 on 2022-12-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0004_alter_studclass_name_alter_student_studclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studclass',
            new_name='Class',
        ),
    ]
