# Generated by Django 4.1.3 on 2022-12-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0006_alter_studclass_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studclass',
            name='id',
        ),
        migrations.AlterField(
            model_name='studclass',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facerecognition.studclass'),
        ),
    ]
