# Generated by Django 4.1.3 on 2022-12-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0009_alter_studclass_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facerecognition.teacher'),
        ),
    ]
