# Generated by Django 4.1.3 on 2022-12-16 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0010_alter_studclass_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 12, 16), null=True),
        ),
    ]
