# Generated by Django 4.1.3 on 2022-12-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0013_rename_id_teacher_t_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='t_id',
            new_name='id',
        ),
    ]
